language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

install:
  - composer selfupdate
  - composer install
  - if [ "$TRAVIS_PHP_VERSION" \> "5.5" ]; then composer require --dev phpunit/phpunit; fi


script:
  - if [ "$TRAVIS_PHP_VERSION" \< "5.6" ]; then composer smoke-test; else composer test; fi
